"""empty message

Revision ID: 2295f55a53a5
Revises: c6094693a544
Create Date: 2017-02-22 11:06:02.937931

"""

# revision identifiers, used by Alembic.
revision = '2295f55a53a5'
down_revision = 'c6094693a544'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic', sa.Column('app_name', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('classified_tag', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('direction', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('dst_b64_payload', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('dst_ip', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('dst_port', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('dst_tcp_flags', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('dst_utf_payload', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('traffic', sa.Column('src_b64_payload', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('src_ip', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('src_port', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('src_tcp_flags', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('src_utf_payload', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('traffic', sa.Column('tag', sa.String(), nullable=True))
    op.add_column('traffic', sa.Column('total_dst_bytes', sa.Integer(), nullable=True))
    op.add_column('traffic', sa.Column('total_dst_pkts', sa.Integer(), nullable=True))
    op.add_column('traffic', sa.Column('total_src_bytes', sa.Integer(), nullable=True))
    op.add_column('traffic', sa.Column('total_src_pkts', sa.Integer(), nullable=True))
    op.drop_column('traffic', 'human_id')
    op.drop_column('traffic', 'prob_bad')
    op.drop_column('traffic', 'ext_metadata')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic', sa.Column('ext_metadata', postgresql.JSON(astext_type=Text()), autoincrement=False, nullable=True))
    op.add_column('traffic', sa.Column('prob_bad', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('traffic', sa.Column('human_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('traffic', 'total_src_pkts')
    op.drop_column('traffic', 'total_src_bytes')
    op.drop_column('traffic', 'total_dst_pkts')
    op.drop_column('traffic', 'total_dst_bytes')
    op.drop_column('traffic', 'tag')
    op.drop_column('traffic', 'start_time')
    op.drop_column('traffic', 'src_utf_payload')
    op.drop_column('traffic', 'src_tcp_flags')
    op.drop_column('traffic', 'src_port')
    op.drop_column('traffic', 'src_ip')
    op.drop_column('traffic', 'src_b64_payload')
    op.drop_column('traffic', 'end_time')
    op.drop_column('traffic', 'dst_utf_payload')
    op.drop_column('traffic', 'dst_tcp_flags')
    op.drop_column('traffic', 'dst_port')
    op.drop_column('traffic', 'dst_ip')
    op.drop_column('traffic', 'dst_b64_payload')
    op.drop_column('traffic', 'direction')
    op.drop_column('traffic', 'classified_tag')
    op.drop_column('traffic', 'app_name')
    ### end Alembic commands ###
