"""empty message

Revision ID: c6094693a544
Revises: 746e2edbd700
Create Date: 2016-11-06 13:56:43.254916

"""

# revision identifiers, used by Alembic.
revision = 'c6094693a544'
down_revision = '746e2edbd700'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic', sa.Column('prob_bad', sa.Float(), nullable=True))
    op.drop_column('traffic', 'flagged')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic', sa.Column('flagged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('traffic', 'prob_bad')
    ### end Alembic commands ###
